FROM node:22-alpine
# used as a base img instead of installing node and do it from STRATCH

WORKDIR /app

COPY . .        
# copy files from original -> docker container

RUN npm install
RUN npm run build

EXPOSE 5050

CMD [ "node", "./dist/index.js" ]
